### ISSUE TITLE
VC Mod Passenger Issue

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#10]
Basically, when a player is in the driver seat a player cannot enter the passanger. Even if they have keys

(running correct VCMod versions with OCRP config)

**Comment by LouisK130** [comment]
The driver of the car must add desired passengers to his buddies list (Q menu).

**Comment by vingard** [comment]
He already did, they can lock or unlock the car and drive it but not get in the passenger seat when somone is in the driver seat.

**Comment by LouisK130** [comment]
Have you installed the VCMod Modifications for OCRP?

Directions are in the readme.

**Comment by vingard** [comment]
Yeah, I have.

**Comment by vingard** [comment]
I get this error ocassionally:

[ERROR] addons/vcmod1/lua/autorun/server/vehcontroller.lua:134: attempt to index field 'VC_Script' (a nil value)
1. EnginePos - addons/vcmod1/lua/autorun/server/vehcontroller.lua:134
   1. FlameAndExplode - gamemodes/ocrp/gamemode/server/cars.lua:1415
   2. DoBreakdown - gamemodes/ocrp/gamemode/server/cars.lua:1242
      1. TakeCarDamage - gamemodes/ocrp/gamemode/server/cars.lua:1483
      2. unknown - gamemodes/ocrp/gamemode/server/player.lua:570

**Comment by LouisK130** [comment]
Do you see

`[UH-OH!] Invalid HitboxSet on something.`

in your console at all when players try to enter the car?

**Comment by vingard** [comment]
No, I think it has something todo with buddies not saving. This error can appear sometimes:

Bad SetLocalOrigin(-4897.606934,-24032.453125,35.177567) on gmod_hands (954)

**Comment by vingard** [comment]
Can I get you on steam maybe? So you can join and see the error?

www.steamcommunity.com/id/thevingard

**Comment by LouisK130** [comment]
VCMod versioning issue. Resolved, updating readme to reflect fix shortly.

**Comment by Loucouss** [comment]
Hey @vingard , please contact me loucouss@gmail.com I wish to bid you $300 for the latest impulse-hl2rp gamemode you have and without any further support. Thanks in advance and best regards
