### ISSUE TITLE
Admin God Stick error

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#13]
[ERROR] gamemodes/ocrp/gamemode/server/cars.lua:912: attempt to index global 'Player' (a function value)
1. fn - gamemodes/ocrp/gamemode/server/cars.lua:912
   1. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

Get this when targeting cars/disabling them, it crashes server.

**Comment by LouisK130** [comment]
Thanks, silly error introduced by one of my later changes. Fixed now, I'll push the change in a second.
