### ISSUE TITLE
Gun animations and userdata errors

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#18]
This error happens in gun fights:
[ERROR] gamemodes/ocrp/gamemode/server/player.lua:642: attempt to compare number with userdata
1. unknown - gamemodes/ocrp/gamemode/server/player.lua:642
   1. FireBullets - [C]:-1
   2. CSShootBullet - gamemodes/ocrp/entities/weapons/weapon_basegun_ocrp/shared.lua:234
      1. unknown - gamemodes/ocrp/entities/weapons/weapon_basegun_ocrp/shared.lua:67

And guns look like this:
http://steamcommunity.com/sharedfiles/filedetails/?id=676519969

Gun in stomach
CSS IS MOUNTED

Also, guns save after death and cannot be traded.

**Comment by LouisK130** [comment]
Okay, those errors were an issue with the body armor system, someone must have been wearing it. I haven't ever looked at that before, so it was completely broken.

The guns in the stomach issue is my fault. I uploaded the wrong content pack. I'm currently uploading the newer one and I will update the readme with the proper link.

The only gun you lose when you die is the one that you are currently holding. You also lose all ammo that is loaded into any gun.

What do you mean by "cannot be traded"? Do you get an error?

**Comment by vingard** [comment]
No, it just does not appear in the trade menu. No error.
