### ISSUE TITLE
Latest update broke gamemode.

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#19]
[ERROR] gamemodes/ocrp/gamemode/server/player.lua:665: '<eof>' expected near 'end'
1. unknown - gamemodes/ocrp/gamemode/server/player.lua:0

Does not connect to the SQL.

**Comment by LouisK130** [comment]
I am unable to reproduce this issue. Ensure you have not modified the file at all. Check line 665 for any characters added by mistake.
