### ISSUE TITLE
Desert Eagle does not work as a weapon and nitrous causes the passenger to die.

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#20]
Deagle does not equip. Also sometimes the drug dealer sells nothing

**Comment by LouisK130** [comment]
I am not able to reproduce this issue with the deagle. It equips fine.

Nitrous issue is likely specific to the car. In which car did you experience this?

The drug dealer is always either selling or buying something. Sometimes he's only buying, and if you don't have the item he's buying, it doesn't show up in the window.

**Comment by vingard** [comment]
Please close.
