### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by darkx239** [LouisK130/Orange-Cosmos-Roleplay#3]
what are the admin commands for this gamemode

**Comment by LouisK130** [comment]
There are no chat commands. Users with ULX ranks of admin, superadmin, or owner will spawn with the godstick SWEP. It looks like a police baton. Right click while holding it to see the admin powers. Select an item from the drop down menu, then left click to perform the selected action.

**Comment by darkx239** [comment]
ok thanks thought the godstick was just for invulnerablity
