### ISSUE TITLE
Database times out in Query

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#34]
Client "Sam" connected (ip censored).

[05/06/16 17:42:01] [TheVingard(STEAM_0:1:95921723)] -> [Local] -> !vip

TheVingard: !vip

Query failed! Attempted: SELECT \* FROM `ocrp_users` WHERE `STEAM_ID` = 'STEAM_0:0:97474497';

Error: Lost connection to MySQL server during query

Dropped Sam from server (An error occured while trying to load your data. Please retry and post on the forums if this problem persists.)

[OCRP] Successfully connected to database.

The database is fully working and I can join and load the user.

Also this:

Query failed! Attempted: UPDATE `ocrp_orgs` SET `owner` = CASE WHEN `orgid` = '1' then 'STEAM_0:1:95921723|TheVingard' END, `applicants` = CASE WHEN `orgid` = '1' then '' END, `perks` = CASE WHEN `orgid` = '1' then '' END, `name` = CASE WHEN `orgid` = '1' then 'The Calibers' END, `orgid` = CASE WHEN `orgid` = '1' then '1' END WHERE `orgid` = '1' ;

Error: MySQL server has gone away

Query failed! Attempted: UPDATE `ocrp_users` SET `blacklist` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `buddies` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `org_id` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1' END, `org_notes` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `refedby` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `face` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'male 6' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'male 6' END, `bank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '295' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '295' END, `skills` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `model` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'models/ocrp2players/clothes1/10/male_06.mdl' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'models/ocrp2players/clothes1/10/male_06.mdl' END, `itembank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `storage` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `wallet` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '200' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '200' END, `nick` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'TheVingard' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'TheVingard' END, `cars` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `inv` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `playtime` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '33' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '33' END, `wardrobe` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1;' WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1;' END WHERE `STEAM_ID` = 'STEAM_0:1:95921723' OR `STEAM_ID` = 'STEAM_0:1:95921723';

Error: Lost connection to MySQL server during query

[OCRP] Successfully connected to database.

Query failed! Attempted: UPDATE `ocrp_users` SET `blacklist` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `buddies` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `org_id` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1' END, `org_notes` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `refedby` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `face` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'male 6' END, `bank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '295' END, `skills` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `model` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'models/ocrp2players/clothes1/10/male_06.mdl' END, `itembank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `storage` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `wallet` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '200' END, `nick` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'TheVingard' END, `cars` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `inv` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `playtime` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '33' END, `wardrobe` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1;' END WHERE `STEAM_ID` = 'STEAM_0:1:95921723' ;

Error: Lost connection to MySQL server during query

[OCRP] Successfully connected to database.

Query failed! Attempted: UPDATE `ocrp_users` SET `blacklist` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `buddies` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `org_id` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1' END, `org_notes` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `refedby` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `face` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'male 6' END, `bank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '295' END, `skills` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `model` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'models/ocrp2players/clothes1/10/male_06.mdl' END, `itembank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `storage` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `wallet` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '200' END, `nick` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'TheVingard' END, `cars` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `inv` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `playtime` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '33' END, `wardrobe` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1;' END WHERE `STEAM_ID` = 'STEAM_0:1:95921723' ;

Error: Lost connection to MySQL server during query

[OCRP] Successfully connected to database.

ServerLog: AWarn: Your server info has been updated to the online statistics tracking

Query failed! Attempted: UPDATE `ocrp_users` SET `blacklist` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `buddies` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `org_id` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1' END, `org_notes` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `refedby` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `face` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'male 6' END, `bank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '295' END, `skills` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `model` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'models/ocrp2players/clothes1/10/male_06.mdl' END, `itembank` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `storage` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `wallet` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '200' END, `nick` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN 'TheVingard' END, `cars` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `inv` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '' END, `playtime` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '33' END, `wardrobe` = CASE WHEN `STEAM_ID` = 'STEAM_0:1:95921723' THEN '1;' END WHERE `STEAM_ID` = 'STEAM_0:1:95921723' ;

Error: Lost connection to MySQL server during query

[OCRP] Successfully connected to database.

**Comment by LouisK130** [comment]
I am unable to replicate this issue. It seems most likely that it is an issue with your SQL server.
