### ISSUE TITLE
Command Issue

### ISSUE THREAD

**Issue by Ribking** [LouisK130/Orange-Cosmos-Roleplay#35]
I am having some Issues with the OC-RP Commands , Could you make a Text Document folder Or something like that for every command in the gamemode ? I've been searching around for around 2 Hours now only to get a few commands and i would appreciate it if you could tell me all the differents commands there are in the Gamemode, Thank you very much.

**Comment by LouisK130** [comment]
https://github.com/LouisK130/Orange-Cosmos-Roleplay/search?utf8=%E2%9C%93&q=concommand

Some of these are outdated or do nothing, some are for development, but you can see them all like this. There aren't very many. Most of the gamemode is menu-based.

**Comment by Ribking** [comment]
Ehm look i dont really know how to like "Use" the command , I am a co-owner at a server and we had the OC-RP done like Yesterday and i am completely new to it and ive been trying to figure out commands for 3 Hours and only getting dissapointing results, So for like, If i try to set someone's money how do i do that do i need to type in console something or in the chat. And how do i get to the sort of "Menu" you were talking about ?

**Comment by LouisK130** [comment]
There are very few console commands. None to give anyone items or money -- the game wasn't designed with the intent of admins cheating for themselves.

The menus are all throughout the gamemode. The primary one is accessed by pressing Q, others are available via F1, F2, F3, F4 and change depending on your circumstances (different job, aiming at different entities, etc).
