### ISSUE TITLE
[Error]

### ISSUE THREAD

**Issue by darkx239** [LouisK130/Orange-Cosmos-Roleplay#4]
Couldn't load Init script

**Comment by LouisK130** [comment]
Please post the entire error and describe the circumstances under which it occurred.

**Comment by darkx239** [comment]
[ERROR] gamemodes/ocrp/gamemode/init.lua:331: attempt to index a nil value
1. unknown - gamemodes/ocrp/gamemode/init.lua:331

Couldn't Load Init Script: 'ocrp/gamemode/init.lua'

**Comment by LouisK130** [comment]
Are you using rp_evocity_v4b1?

**Comment by darkx239** [comment]
yes

**Comment by darkx239** [comment]
is something wrong with v4b1

**Comment by LouisK130** [comment]
No, v4b1 is the only supported map. Are you certain the map file is named exactly rp_evocity_v4b1?

**Comment by darkx239** [comment]
sorry forgot switched the map
