### ISSUE TITLE
Sql data store not editable 

### ISSUE THREAD

**Issue by GoproMgH** [LouisK130/Orange-Cosmos-Roleplay#45]
Hello can you help change the code or tell me how to to make the user data editable like genes money and other stuff

**Comment by LouisK130** [comment]
You need to manually edit the SQL database. Find an SQL client that lets you do this (PHPMyAdmin, HeidiSQL, etc).

Run "ocrp_forcesqlpush" from the server console, then edit the player rows of your choice. Ensure that the player(s) whose rows you are editing are not online while you do it, else your changes may be overwritten.

**Comment by GoproMgH** [comment]
well i used phpmyadmin and when i double click on my money amount for my guy it doesnt edit it

**Comment by Segeco** [comment]
You need to set a default value in the database i believe, Not sure.

**Comment by GoproMgH** [comment]
can you add me on steam its not working for me https://steamcommunity.com/profiles/76561198068444451
