### ISSUE TITLE
Fix Strafe

### ISSUE THREAD

**Issue by Segeco** [LouisK130/Orange-Cosmos-Roleplay#48]
Fix the error when holding W or S and A or D and it bugs.

**Comment by LouisK130** [comment]
This is only while sprinting, correct?

**Comment by Segeco** [comment]
Yep :)

**Comment by Segeco** [comment]
Nope
walking aswell :dancers:

**Comment by LouisK130** [comment]
Ok, I don't have much time but I'll start looking into some of these smaller issues.
