### ISSUE TITLE
BOT

### ISSUE THREAD

**Issue by Segeco** [LouisK130/Orange-Cosmos-Roleplay#49]
I know this is petty, but can you add an if statement during client loading to check if it's a bot and set it to a citizen. (I'm trying some animations:))

**Comment by LouisK130** [comment]
Look through these two functions. Both have checks that stop them from running at all if the player is a bot. The gamemode is not designed to support bots.

https://github.com/LouisK130/Orange-Cosmos-Roleplay/blob/master/ocrp/gamemode/server/player.lua#L272-L413
