### ISSUE TITLE
Re supply & NPCS

### ISSUE THREAD

**Issue by Segeco** [LouisK130/Orange-Cosmos-Roleplay#50]
Can you allow us to set the models of the npc's? And while using M9K no ammo works from the re supply station. Sorry ;)

**Comment by LouisK130** [comment]
NPC's are created here: https://github.com/LouisK130/Orange-Cosmos-Roleplay/blob/master/ocrp/gamemode/shared.lua#L600-L631

Using this function: https://github.com/LouisK130/Orange-Cosmos-Roleplay/blob/master/ocrp/gamemode/server/npcs.lua#L8-L63

**Comment by Segeco** [comment]
Can you please add an option for a model?

**Comment by LouisK130** [comment]
The 8th parameter to that function is the model to be used.
