### ISSUE TITLE
QUESTION: Web Panel

### ISSUE THREAD

**Issue by Segeco** [LouisK130/Orange-Cosmos-Roleplay#51]
Hey, Can i have your steam? - I'd like to talk to you regarding some additions to the gamemode. (PM Me if you want)

**Comment by LouisK130** [comment]
I have little time for substantial additions to the gamemode currently.

**Comment by Segeco** [comment]
I mean, me creating them.

**Comment by LouisK130** [comment]
http://steamcommunity.com/id/realdope/
