### ISSUE TITLE
Location of init side code for bank property npc

### ISSUE THREAD

**Issue by GoproMgH** [LouisK130/Orange-Cosmos-Roleplay#55]
where is it?

**Comment by LouisK130** [comment]
Not sure what you mean by "init side". Typically "side" is prefixed be either client or server..

Check out 
https://github.com/LouisK130/Orange-Cosmos-Roleplay/blob/master/ocrp/gamemode/server/property.lua
https://github.com/LouisK130/Orange-Cosmos-Roleplay/blob/master/ocrp/gamemode/client/property.lua
