### ISSUE TITLE
SQL issues

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#6]
Getting error:

> [ERROR] gamemodes/ocrp/gamemode/server/mysql_handle.lua:9: attempt to index local 'q' (a nil value)
> 1. runOCRPQuery - gamemodes/ocrp/gamemode/server/mysql_handle.lua:9
> 2. fn - gamemodes/ocrp/gamemode/server/mysql_handle.lua:353
> 3. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

 on startup
**
sql handle file:**

http://pastebin.com/50TpKZJm

**PHPMYADMIN STUFF:**
screenshots

http://pasteboard.co/tECwPgt.png

http://pasteboard.co/tEElNdU.png

**Comment by LouisK130** [comment]
Please pastebin your whole console on startup and double check your SQL credentials are correct.

**Comment by vingard** [comment]
Startup: http://pastebin.com/6Vxm2jxb

I've checked my SQL several times now and made new users, repaired databse ect.

**Comment by LouisK130** [comment]
Please try the latest version with a full restart of your server. You should find an error in your console on startup.

**Comment by vingard** [comment]
Hello again, fully updated and restarted but gives: 

[ERROR] gamemodes/ocrp/gamemode/server/mysql_handle.lua:18: attempt to index local 'q' (a nil value)
1. runOCRPQuery - gamemodes/ocrp/gamemode/server/mysql_handle.lua:18
   1. fn - gamemodes/ocrp/gamemode/server/mysql_handle.lua:362
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

I think it's colliding with ULX or something? Maybe it could only run on an old version?

Also I got no OCRP ERRORS.

Thanks again.

**Comment by LouisK130** [comment]
Hm, that's quite strange. I doubt it's an issue with ULX.

Do you not even see a message saying connection was successful? Try intentionally making your credentials or IP wrong and tell me if you get an error message then. Restart after changing the file.

**Comment by vingard** [comment]
Hello, changed the IP to a fake one and got this message:

[OCRP] Connection to database failed.

[OCRP] Error: Unknown MySQL server host '198.91.81.7delete' (0)

But stil, got this error:

[ERROR] gamemodes/ocrp/gamemode/server/mysql_handle.lua:18: attempt to index local 'q' (a nil value)
1. runOCRPQuery - gamemodes/ocrp/gamemode/server/mysql_handle.lua:18
   1. fn - gamemodes/ocrp/gamemode/server/mysql_handle.lua:362
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:105

With the normal IP I get no OCRP message, yet it still fails to connect.

**Comment by LouisK130** [comment]
Ok. I believe the connection is timing out, so it never fails or succeeds and we get no message. Are you certain your SQL server is configured to accept connections from the IP of your server? Can other addons or gamemodes connect?

**Comment by vingard** [comment]
Yeah, Remote SQL is enabled, http://pasteboard.co/tECwPgt.png

I don't really have any other addons to test it with, as OCRP is the only thing on the server using MySql, I'll try to look for an alternative database host now.

**Comment by vingard** [comment]
Ah sorted!

[OCRP] Loaded org data from database.

[OCRP] Successfully connected to database.

That's great thanks for all the help here mate, your a hero :+1:

**Comment by vingard** [comment]
One last thing, where is the + button on the skills?

http://steamcommunity.com/sharedfiles/filedetails/?id=673964078

**Comment by LouisK130** [comment]
I'm glad it worked out.

You must buy books to learn a skill before you can upgrade them. Books are sold by the librarian NPC in the building across the street from the Nexus. A few random books are sold at a time, rotating every 10 minutes or so.

**Comment by vingard** [comment]
Sorry for all the questions, how do you find clay/metal? also does the Vanilla OCRP contain the Character Name system? Thanks :P
Oh, and money trading does not work for me.

**Comment by LouisK130** [comment]
Clay and metal are sold by the materials vendor (an NPC up the hill in the city, next to the garage). There is not currently an RP name system.

In what way does money trading not work? Does item trading?

**Comment by LouisK130** [comment]
Please open a new issue if you have further problems with trading, as that's a separate topic.
