### ISSUE TITLE
Bank Vault, and several skills.

### ISSUE THREAD

**Issue by clunkyy** [LouisK130/Orange-Cosmos-Roleplay#62]
I've been looking around the map and I cannot find the bank vault anywhere,

Also I did find the librarian with the skill books, but it only has 3 books.

Do the other books have locations? If so where would they be, and where is the vault located?

**Comment by clunkyy** [comment]
Also cant find any NPC that sells weed

**Comment by JoePale** [comment]
Npc that sells weed is behind the apts, at this like corner section, just look for it behind the apts

**Comment by LouisK130** [comment]
I'm not sure what bank vault you're looking for. As Joe pointed out, the drug dealer is behind the apartments. The librarian's books for sale rotate every 10-15 minutes. Just keep checking back and eventually he'll be selling the one you're looking for.

NPC locations are easily modified.

**Comment by clunkyy** [comment]
How about the other two things..?

**Comment by clunkyy** [comment]
I guess by vault I would mean "Mayor Cash Blocks".

**Comment by LouisK130** [comment]
Oh. To be completely honest I don't remember. It's either the bank on main street or in one of the office rooms at the top of the nexus building.

**Comment by clunkyy** [comment]
Sounds good, one last question. Why is it that fire is missing textures for my players? Is their an addon I should add to my fastDL?
