### ISSUE TITLE
VCMod not working? explain how to install in detail?

### ISSUE THREAD

**Issue by JoePale** [LouisK130/Orange-Cosmos-Roleplay#63]
So I tried installing VCMod and VCMod ELS and tried to follow the guide, but all I got was script errors when adding in the old modifications to the addons, and VCMOD was just not present? 

Could someone explain in great detail on how I would go about installing both VCMod and VCMod ELS?

**Comment by BloodySenatu** [comment]
If you are using linux (best to assume so in most situation), make sure that the folder names are in lowercase.

Also make sure you are using the version specified in the readme on the main page of the deposit.

> VCMod (Compatible with 1.735 but not any of the newer versions)
> VCMod ELS (Compatible with 1.123 but not any of the newer versions)

**Comment by LouisK130** [comment]
As pointed out above, versions past 1.735 and 1.123 (main and ELS, respectively) are not tested/supported.

The installation is relatively simple, as described in steps 3-5 in the readme.
