### ISSUE TITLE
The logo and bar that comes down from the top

### ISSUE THREAD

**Issue by clunkyy** [LouisK130/Orange-Cosmos-Roleplay#64]
Which file contains the notification that says to go to "ZetaGaming.com"

And where is the logo file?

**Comment by LouisK130** [comment]
https://github.com/LouisK130/Orange-Cosmos-Roleplay/search?utf8=%E2%9C%93&q=zetagaming

Art is in materials/gui/OCRP

**Comment by clunkyy** [comment]
Strange, I changed it and did a websync. The images are still the same.

**Comment by LouisK130** [comment]
Material caching on the client can be weird in garrysmod. I can't help you much. Try deleting the existing file on your client and joining the server to force a download of the new one.

If you update the file on the server, new players joining should get the new version, even if the old one is still cached for you.
