### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by vingard** [LouisK130/Orange-Cosmos-Roleplay#9]
Hi, my SQL and stuff is all good but I get these errors when people die/get knocked out.

[ERROR] gamemodes/ocrp/gamemode/server/death.lua:135: attempt to index field 'KOInfo' (a nil value)
1. unknown - gamemodes/ocrp/gamemode/server/death.lua:135

and

 [ERROR] gamemodes/ocrp/gamemode/server/inventory.lua:223: attempt to index field 'OCRPData' (a nil value)
1. HasItem - gamemodes/ocrp/gamemode/server/inventory.lua:223
   1. unknown - gamemodes/ocrp/gamemode/server/chat.lua:237

**Comment by LouisK130** [comment]
Do these errors persist through a full restart?

**Comment by vingard** [comment]
No, they start happening when someone dies/gets knocked out. Also they get the respawn timer and at the end it says "Waking up" forever.

**Comment by LouisK130** [comment]
I understand, but have you tried restarting your server? I cannot reproduce this issue.
